site_name: Roger Perkin Network Automation Document Portal
#site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme: 
  name: material 

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: slate  # Set dark mode as default (slate is a dark theme)
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: "#003366" 
      accent: lime

    - scheme: default  # This is the light mode scheme, for toggling
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/rogerperkin"  target="_blank" rel="noopener">Roger Perkin GitHub</a>

